- src/pages/forget-password/forget-password.html
- src/pages/forget-password/forget-password.ts
- src/pages/login/login.html
- src/theme/main.styles.theme.scss
[PE-142] hotfix for forgot password back button
> [PE-142] hotfix for forgot password back button

- src/app/app.module.ts
- src/pages/activities/list/list.html
- src/pages/activities/list/list.page.ts
- src/pages/activities/list/popover-text.ts
- src/theme/main.styles.theme.scss
[PE-143] Feature/dashboard page customise
> [PE-143] Feature/dashboard page customise

- src/pages/activities/list/list.html
- src/pages/activities/list/list.page.ts
> Add tick for new activity

- src/pages/activities/list/list.html
> Change tick colors

- src/pages/assessments/assessments.page.ts
we should look into test script soon, the statuses getting more complicated now.
> [PE-155] more extended statuses filter

- src/pages/activities/view/activities-view.page.ts
- src/pages/activities/view/view.html
Bugfix for showing correct icon in activity detail page
> Bugfix for showing correct icon in activity detail page

- src/pages/activities/view/view.scss
> CSS update for activity logo

- src/pages/activities/view/activities-view.page.ts
- src/pages/activities/view/view.html
Change submission title to review result
> ChangeSubmissionTitle

- src/pages/activities/view/activities-view.page.ts
- src/pages/activities/view/view.html
- src/pages/activities/view/view.scss
> Add Result Tag

- src/pages/activities/view/activities-view-modal.page.ts
- src/pages/activities/view/activities-view-model.html
- src/pages/activities/view/activities-view.page.ts
- src/pages/activities/view/view.scss
- src/pages/assessments/assessments.scss
- src/pages/assessments/group/assessments-group.scss
- src/theme/main.styles.theme.scss
[PE-145] Feature/customise activity details
> [PE-145] Feature/customise activity details

- src/pages/assessments/assessments.scss
- src/pages/assessments/group/assessments-group.html
- src/theme/main.styles.theme.scss
[PE-159] feature/question and answer page styling tiny changes
> [PE-159] feature/question and answer page styling tiny changes

- src/pages/activities/list/list.html
- src/pages/activities/list/list.page.ts
- src/pages/assessments/group/assessments-group.html
- src/pages/tabs/tabs.page.ts
- src/theme/main.styles.theme.scss
- src/theme/practera.theme.default.scss
[PE-160] restyling items spin popup model page
> [PE-160] restyling items spin popup model page

- src/pages/activities/list/instruction/instruction.page.ts
- src/pages/activities/list/list.page.ts
- src/pages/activities/list/popup.ts
- src/pages/activities/view/activities-view-modal.page.ts
- src/pages/activities/view/activity-achievement.modal.page.ts
- src/pages/assessments/group/assessments-group.page.ts
- src/pages/assessments/popup/items-popup.page.ts
- src/pages/events/download/events-download.page.ts
- src/pages/events/list/list.page.ts
- src/pages/events/view/events-view.page.ts
- src/pages/rankings/list/rankings.page.ts
- src/pages/rankings/view/ranking-badges.ts
- src/pages/settings/tutorial/tutorial.page.ts
- src/services/milestone.service.ts
[PE-168] bugfix/exclude attended events into total booking count and remove unnecessary console logs
> [PE-168] bugfix/exclude attended events into total booking count and remove unnecessary console logs

- src/pages/rankings/list/rankings.page.ts
- src/services/game.service.ts
https://intersective.atlassian.net/browse/PE-170
> [PE-170] Leaderboard returning all time ranking rather then monthly ranking

- src/components/questions/feedback.html
- src/pages/assessments/group/assessments-group.html
- src/theme/main.styles.theme.scss
[PE-172] bugfix/improve assessment feedback styling
> [PE-172] bugfix/improve assessment feedback styling

- src/pages/events/view/events-view.html
https://intersective.atlassian.net/browse/PE-179
> Hide capacity message and also book button [PE-179]

- src/pages/activities/list/instruction/instruction.page.ts
- src/pages/settings/settings.page.ts
- src/pages/settings/tutorial/tutorial.page.ts
https://intersective.atlassian.net/browse/PE-178
> [PE-178] Fix active dashboard page when back from tutorial

- package-lock.json
- package.json
- src/pages/spinwheel/spinwheel.page.ts
- yarn.lock
- during spinning phase, additional click is not allowed.
> [PE-186] added spin attempt checking

- src/assets/i18n-en.json
- src/pages/events/view/events-view.html
- src/pages/events/view/events-view.page.ts
https://intersective.atlassian.net/browse/PE-180
> [PE-180] Disable checkin button

- src/assets/i18n-en.json
- src/pages/events/list/list.html
- src/pages/events/list/list.page.ts
https://intersective.atlassian.net/browse/PE-188
> [PE-188] Location filter for browse events

- src/app/messages.ts
- src/pages/assessments/assessments.page.ts
https://intersective.atlassian.net/browse/PE-193
> Content submit popup [PE-193]

- src/pages/events/list/list.html
> [PE-195] Feature/filtering icon

- src/pages/events/view/events-view.html
https://intersective.atlassian.net/browse/PE-201
> [PE-201] Checkout and cancel hidden when event is fully booked

- src/services/game.service.ts
https://intersective.atlassian.net/browse/PE-202
> [PE-202] Possible error in ranking page

- src/pages/activities/list/list.page.ts
- src/pages/assessments/assessments.page.ts
> [PE-199] Feature/assessment-submission

- src/pages/activities/list/list.html
- src/pages/activities/list/list.page.ts
updates:
- bookings
- points
- grades
> [PE-213] feature/score boards updates

- src/pages/activities/list/list.html
- src/pages/activities/list/list.scss
https://intersective.atlassian.net/browse/PE-213
> [PE-213] Update booking style

- src/pages/activities/list/list.page.ts
- src/pages/events/view/events-view.html
- src/pages/events/view/events-view.page.ts
https://intersective.atlassian.net/browse/PE-215
> [PE-215] Fix missing cancel button

- src/pages/activities/list/list.html
- src/theme/activity/all.scss
- size restriction with height in percentage unit is not compatible with safari 10 browser (mobile)
- removing size restriction in ion-header works even better (more responsive) than restricting it into 50% height of the screen
> removed size restriction

- src/app/app.module.ts
- src/pages/activities/list/list.html
- src/pages/activities/list/list.page.ts
- src/pages/activities/list/new-items/new-items.html
- src/pages/activities/list/new-items/new-items.page.ts
- src/pages/events/list/list.html
- src/theme/pages/event.scss
https://intersective.atlassian.net/browse/PE-220
> [PE-220] Location button block by menu

- package-lock.json
- src/assets/js/piwik.js
- src/configs/config.ts
- src/index.html
Changes
[PE-272] added location name at event card list 
[PE-273] prepended "info" text for (i) label
> Release 26-06-2018

- src/pages/assessments/assessments.page.ts
- src/services/assessment.service.ts
removal audience check which is no longer required and it caused bug if we still keep the checking in the code, as API will smartly return different set of questions based on login-ed user.
> [PE-280] feature/remove audience check

- package-lock.json
- src/components/questions/file.ts
- src/configs/config.ts
- src/index.html
- src/pages/activities/list/list.page.ts
- src/pages/activities/view/activities-view.page.ts
- src/pages/assessments/assessments.page.ts
- src/pages/events/view/events-view.html
- src/pages/magic-link/magic-link.ts
- src/services/assessment.service.ts
- src/shared/filestack/filestack.service.ts
changelogs
- Filestack version upgrade
bugfixes
- [PE-286] on 2nd submission, reviewer question display on student assessment
- [PE-283] unable to book even when it's not readonly mode
> Release: 2019-03-07

- src/pages/login/login.html
removed new user link from login screen.
> [PE-290] Remove "New User" link

- src/pages/activities/list/list.html
- src/pages/activities/list/list.page.ts
- src/pages/login/login.html
Changelog
- [PE-288] minimum submission, get 2.5 if first one is passed.
- [PE-290] removed new user link in login screen
> Master dev updates

- src/pages/assessments/assessments.page.ts
trials
- returning whole 'AssessmentSubmissionAnswer' empty object, but gets 'Notice (8): Undefined index: assessment_question_id' instead
- tried with different empty answer value `'', null, {}` none work
> [PE-293] feature/empty-submission-failed

- src/pages/assessments/assessments.page.ts
Changelogs
[PE-293] Optional submission unable to be let empty
> Master develop updates

- src/configs/config.ts
- src/pages/activities/list/list.html
- src/pages/activities/list/list.page.ts
- src/pages/activities/list/popover-text.ts
- src/pages/activities/view/activities-view.page.ts
- src/pages/activities/view/view.html
- src/pages/activities/view/view.scss
- src/pages/login/login.html
- src/services/achievement.service.ts
changes
- [PE-288] scoring updates(minimum submission be4 request portfolio allowed)
- [PE-290] new user link removal from login screen
- [PE-292] show tick for completed newbie assessment
- [PE-293] allow empty optional assessment submission 
- updated `what is this?` (for portfolio) popup message
> Release-2019_04_03

- src/pages/settings/settings.html
- src/pages/settings/settings.page.ts
- src/pages/settings/settings.scss
- src/services/auth.service.ts
- added mew methods to auth service to update profile.
- added new statement to get local user data to settings page.
- created new method to call service profile update method.
- create a method to show filestack popup.
> [PE-291] Add profile picture upload

- src/pages/registration/register.page.ts
- src/pages/term-condition/term-condition.html
- src/pages/term-condition/term-condition.page.ts
- src/services/auth.service.ts
https://intersective.atlassian.net/browse/PE-295
> [PE-295] Feature/prompt reset

- src/pages/login/login.ts
- src/pages/registration/register.page.ts
- src/services/game.service.ts
- src/services/milestone.service.ts
2 apikey in the case of registration
- first is the one received for registration
- 2nd (new) one is used of every other functional API call
> [PE-295] reset key to the new one after the first one

- hooks/post-build.js
- src/index.html
https://intersective.atlassian.net/browse/PE-298
> [PE-298] assets timestamp

- src/app/app.module.ts
- src/components/event/event.component.ts
- src/components/event/event.html
- src/components/event/img.directive.ts
https://intersective.atlassian.net/browse/PE-300
> [PE-300] added imgDirective to standardise errorHandling

- src/pages/login/login.ts
- src/pages/settings/settings.page.ts
- src/shared/cache/cache.service.ts
https://intersective.atlassian.net/browse/PE-305
> [PE-305] show tutorial page at first login

- src/pages/login/login.ts
- src/pages/registration/register.page.ts
https://intersective.atlassian.net/browse/PE-305
> [PE-305] display after registration only

- src/pages/activities/list/list.page.ts
- src/pages/login/login.html
- src/pages/login/login.ts
- src/services/auth.service.ts
https://intersective.atlassian.net/browse/PE-307
> [PE-307] display experience image or 'default practera logo'

- package-lock.json
- package.json
- src/app/app.module.ts
- src/assets/i18n-en.json
- src/directives/custom-logo/custom-logo.directive.html
- src/directives/custom-logo/custom-logo.directive.ts
- src/pages/forget-password/forget-password.html
- src/pages/forget-password/forget-password.scss
- src/pages/forget-password/forget-password.ts
- src/pages/login/login.html
- src/pages/login/login.ts
- src/pages/registration/register.html
- src/shared/cache/cache.service.ts
- src/theme/appv2.scss
- src/theme/auth/user.scss
- src/theme/main.styles.theme.scss
https://intersective.atlassian.net/browse/PE-308
> [PE-308] Task/reset-password-enhancement

- src/assets/i18n-en.json
- src/pages/registration/register.html
- src/pages/registration/register.page.ts
- src/pages/registration/registration.page.ts
https://intersective.atlassian.net/browse/PE-309
> [PE-309] registration-page-enhancement

- src/pages/activities/view/activities-view-modal.page.ts
- src/pages/activities/view/activities-view-model.html
https://intersective.atlassian.net/browse/PE-310
> [PE-310] feature/html code in description

- package-lock.json
- src/app/app.module.ts
- src/pages/assessments/assessments.page.ts
- src/pages/spinwheel/spinwheel.page.ts
- src/pages/spinwheel/spinwheel.scss
- src/pages/tabs/tabs.html
- src/pages/tabs/tabs.page.ts
- src/services/auth.service.ts
- src/shared/cache/cache.service.ts
the changes involved:
[PE-315] popover box appear at wrong location on desktop screen randomly
[PE-316] display spinwheel based on custom color retrieved from remote config
[PE-315]: https://intersective.atlassian.net/browse/PE-315
[PE-316]: https://intersective.atlassian.net/browse/PE-316
> [PE-315] Bugfix/unfixed-position

- src/app/default.ts
- src/configs/config.ts
- src/pages/term-condition/term-content.component.ts
https://intersective.atlassian.net/browse/PE-318
> [PE-318] fixed helpline

- src/pages/activities/list/new-items/new-items.html
- src/pages/activities/list/new-items/new-items.page.ts
- src/pages/assessments/assessments.page.ts
[PE-319] https://intersective.atlassian.net/browse/PE-319
[PE-319]: https://intersective.atlassian.net/browse/PE-319
> [PE-319] task/spinner-image

- README.md
- src/components/questionGroup/questionGroup.html
- src/components/questionGroup/questionGroup.scss
- src/theme/assessment/group.scss
- src/theme/assessment/list.scss
- src/theme/popup.scss
- src/theme/variables.scss
[PE-317] https://intersective.atlassian.net/browse/PE-317
[PE-317]: https://intersective.atlassian.net/browse/PE-317
> (confirmation required) [PE-317] task/main-text-in-dark-gray

- src/components/event/event.component.ts
- src/components/event/event.html
- src/pages/activities/list/new-items/new-items.html
- src/pages/activities/list/new-items/new-items.page.ts
- src/pages/events/list/list.page.ts
- src/theme/popup.scss
https://intersective.atlassian.net/browse/PE-320
> [PE-320] Task/event-banner

- src/components/event/event.component.ts
- src/components/event/event.html
- src/pages/activities/list/new-items/new-items.html
- src/pages/activities/list/new-items/new-items.page.ts
- src/pages/events/list/list.page.ts
- src/theme/popup.scss
Reverts jazzmind/personal-edge#283
for test changes release
> Revert "[PE-320] Task/event-banner"

- src/components/event/event.component.ts
- src/components/event/event.html
- src/pages/activities/list/new-items/new-items.html
- src/pages/activities/list/new-items/new-items.page.ts
- src/pages/events/list/list.page.ts
- src/theme/popup.scss
[PE-320] use first attachment image as event's banner + new spinner award btn to use custom color
[PE-320]: https://intersective.atlassian.net/browse/PE-320
> Release preparation [PE-320]

- README.md
- src/app/app.component.ts
- src/pages/activities/list/list.html
- src/pages/activities/list/list.page.ts
- src/services/auth.service.ts
- src/theme/core.scss
https://intersective.atlassian.net/browse/PE-323
> [PE-323] Feature/custom-header

- src/pages/magic-link/magic-link.ts
- src/services/auth.service.ts
https://intersective.atlassian.net/browse/PE-324
> [PE-324] fixed magiclink login

- Dockerfile
- README.md
- docker-compose.yml
- package.json
- src/pages/activities/list/list.html
- src/pages/activities/list/list.page.ts
- src/pages/activities/view/activity-achievement.modal.page.ts
- src/pages/events/list/list.page.ts
- src/services/auth.service.ts
https://intersective.atlassian.net/browse/PE-329
> [PE-329] Feature/min-scoring

- Dockerfile
- src/configs/config.ts
- src/pages/activities/list/list.html
- src/pages/activities/list/list.page.ts
- src/pages/activities/view/activity-achievement.modal.page.ts
- src/pages/events/list/list.page.ts
PE-329 - one submissiom + review for each skill unlock portfolio request
> Release-2021_06_21

- Dockerfile
- src/configs/config.ts
- src/pages/activities/list/list.html
- src/pages/activities/list/list.page.ts
- src/pages/activities/view/activity-achievement.modal.page.ts
- src/pages/events/list/list.page.ts
https://intersective.atlassian.net/browse/PE-329
> [PE-329] feature/min-score
